const HouseData = [
  {
    id: 1,
    name: "The Wallace",
    price: "3 900 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Christiana",
      Estate: "Soka Game Reserve",
      State: "North West",
      PostAdress: "2690",
    },
    bedrooms: "4",
    img: require(),
  },
  {
    id: 2,
    name: "The White One",
    price: "5 000 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Jan Kemp Dorp",
      Estate: "Naledi Street",
      State: "Northen Cape",
      PostAdress: "2691",
    },
    bedrooms: "6",
    img: require(),
  },
  {
    id: 3,
    name: "Die Plaas Huis",
    price: "R2 560 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Bloemhof",
      Estate: "Van tar farm",
      State: "Virginia",
      PostAdress: "1733",
    },
    bedrooms: "3",
    img: require(),
  },
  {
    id: 4,
    name: "Pixalary",
    price: "6 000 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Cape Town",
      Estate: "The Hills",
      State: "Vasily",
      PostAdress: "1290",
    },
    bedrooms: "10",
    img: require(),
  },
  {
    id: 5,
    name: "Fairwell",
    price: "1 200 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Texas",
      Estate: "Rose Lily",
      State: "York",
      PostAdress: "4590",
    },
    bedrooms: "3",
    img: require(),
  },

  {
    id: 6,
    name: "The Glory",
    price: "2 800 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "New York",
      Estate: "Hamptons",
      State: "New York",
      PostAdress: "0001",
    },
    bedrooms: "5",
    img: require(),
  },
  {
    id: 7,
    name: "Sunset Fell",
    price: "800 000",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Athens",
      Estate: "Sokris",
      State: "Paplo",
      PostAdress: "2290",
    },
    bedrooms: "2",
    img: require(),
  },
  {
    id: 8,
    name: "The Marchent",
    price: "5 200 200",
    info: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam adipisci at facere. Quisquam itaque, delectus vero tempora ut aliquam odio.`,
    location: {
      City: "Pretoria",
      Estate: "Vel da vie",
      State: "Gauteng",
      PostAdress: "8326",
    },
    bedrooms: "6",
    img: require(),
  },
];
